# Generated by Django 5.1.1 on 2024-10-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airsoft', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
